Implement try..catch in props of type function
selsa-inube/inubekit-tabs pull request #3
Opened 2024-03-08 16:59 UTC by cmarin001

This pull request details a strategic enhancement to our application's components by implementing try..catch blocks within function-type props. Aimed at bolstering error handling and ensuring graceful degradation of component functionality in error scenarios, this update significantly contributes to the robustness and reliability of our application, enhancing the user experience by preventing unexpected crashes and errors.

2024-03-14 01:50 UTC, JanuarAsprilla commented on vite.config.ts
>          "styled-components",
`"react-dom"` and `"react-icons"` are needed

2024-03-15 16:22 UTC, wfercanas requested changes
The implementation of Tabs with buttons to scroll left and right is not aligned with the design of the component.
The buttons help the user scroll, but those button shouldn't change the selected tab. That change can only be done when the user clicks in the tab he/she wants to see.

Refactor the component so the buttons support the scroll. 


Solved

2024-03-15 22:25 UTC, JanuarAsprilla approved these changes

2024-03-19 19:31 UTC, wfercanas commented on src/Tabs/props.ts
> +const types = ["select", "tabs"] as const;
Let's remove this prop and create the `scroll` prop just like in figma.
That prop is of type boolean.

2024-03-19 19:34 UTC, wfercanas commented on src/Tabs/index.tsx
>    if (type === "select") {
This return for a `type==="select"` can be deleted. There will be no select variant for the component.

2024-03-19 21:13 UTC, cmarin001 commented on src/Tabs/props.ts
> +const types = ["select", "tabs"] as const;
solved

2024-03-19 21:15 UTC, cmarin001 commented on src/Tabs/index.tsx
> +  showChevrons = false,
solved

2024-03-19 21:15 UTC, cmarin001 commented on src/Tabs/index.tsx
>    if (type === "select") {
solved

2024-03-19 21:27 UTC, cmarin001 commented on src/Tabs/Tab/styles.js
> +    `4px solid ${theme?.palette?.blue?.B400 || inube.palette.blue.B400}`};
solved

2024-03-19 22:16 UTC, JanuarAsprilla approved these changes

2024-03-20 16:33 UTC, wfercanas requested changes

2024-03-20 16:33 UTC, wfercanas commented on src/Tabs/Tab/index.tsx
> +      $appearance={inube.tabs.content.appearance}
The usage of the tabs token isn't correct in this component.
The tabs token define the appearance of the selected tab, that appearance is a string like "primary", "success", "help", etc.

**We have to:**
1. Get that value from the context of styled-components, because that value is the one we should use to define the appearance of Text. Othewise, it doesn't matter how the client defines the token, we can only use inube tokens for Text appearance.
2. StylesTab doesn't have to get that value through props, because we can get it using `theme` in the callback of the styled component. Right there, we have to define the border-bottom of the selected tab using the tab token. How? assigning the color with that appearance and the text.color[appearance] value.

**Extra:**
If we don't get a value from the theme, then we can use the inube tokens as fallback for defining the appearance of Text

2024-03-20 17:24 UTC, cmarin001 commented on src/Tabs/Tab/index.tsx
> +      $appearance={inube.tabs.content.appearance}
solved

2024-03-20 17:40 UTC, JanuarAsprilla approved these changes

2024-03-26 14:59 UTC, wfercanas requested changes

2024-03-26 14:59 UTC, wfercanas commented on src/Tabs/Tab/styles.js
> +import { Text } from "@inubekit/text";
Text is defined but not used

2024-03-26 14:59 UTC, wfercanas commented on src/Tabs/Tab/styles.js
> +      inube.text[inube.tabs.content.appearance.selected].content.color.regular
We can simplify here, avoiding to get the vales from inube tokens twice: once in index.tsx and twice here.

In index.tsx we can create a variable like selectedAppearance and save there the value of the token. That value can be used in the props for Text and also passed as props to StyledTab.

**Extra:** that value cannot simply be just like
```js
const selectedAppearance = inube.tabs.content.appearance.selected
```

This is because the component would only be able to use the selected value of inube, not from the theme. Assuming (you have to search how it really works) that the context for themes is ThemeContext, we will need to do something like:

```js
const Tab = () => {
  // .....
  const theme = useContext(ThemeContext)
  const selectedAppearance = 
    theme.tabs.content.appearance.selected ||
    inube.tabs.content.appearance.selected
  
  // ....
}
```

2024-03-26 16:05 UTC, cmarin001 commented on src/Tabs/Tab/styles.js
> +import { Text } from "@inubekit/text";
solved

2024-03-26 16:52 UTC, cmarin001 commented on src/Tabs/Tab/styles.js
> +      inube.text[inube.tabs.content.appearance.selected].content.color.regular
solved

2024-03-26 21:56 UTC, wfercanas approved these changes

2024-03-26 21:56 UTC, merged