Adjust and export interfaces
selsa-inube/inubekit-tabs pull request #5
Opened 2024-03-21 22:10 UTC by JanuarAsprilla

The names of the interfaces used by the `<Tabs />` component were refactored, as well as how they are exported.

2024-03-26 15:04 UTC, wfercanas requested changes

2024-03-26 15:04 UTC, wfercanas commented on src/Tabs/index.tsx
> +export type { ITabsTypes, ITabs };
There is no need to re-export here ITabsTypes. That interface is not defined in this file, so it shouldn't be its responsibility.

2024-03-26 15:04 UTC, wfercanas commented on src/Tabs/props.ts
> +type ITabsTypes = (typeof types)[number];
We deleted the `ITabsTypes` prop from the component and added a scroll prop that is boolean.
Pull the recent changes in main and adjust your PR.

2024-03-29 22:02 UTC, JanuarAsprilla commented on git
solved

2024-04-01 15:34 UTC, wfercanas approved these changes

2024-04-01 15:34 UTC, merged